Implemented grep flags: lLHxwv.

diff --git a/grep2awk b/grep2awk
--- a/grep2awk
+++ b/grep2awk
@@ -2,71 +2,118 @@ emulate -L zsh
 setopt extendedglob
 autoload -Uz split-shell-arguments
 
-#[[ -f log ]] && rm log
-
 change_regex() {
-    re="/${(Q)1}/ {}"
-    printf ${(qq)re}
+    re=${(Q)1}
+    (( opt[w] > 0 )) && {
+        re="\\<($re)\\>" 
+    }
+    (( opt[x] > 0 )) && {
+        re="^($re)$"
+    }
+    re="/$re/"
+    (( opt[v] > 0 )) && {
+        re="!$re"
+    }
+    action="{}"
+    # H, l and L are mutually exclusive. One of the will win. 
+    # TODO: Maybe should fail here explicitly:
+    #
+    #    (( opt[H] + opt[l] + opt[L] > 1 )) && exit 1
+
+    (( opt[H] > 0 )) && {
+        action='{print FILENAME":"$0}'
+    }
+    (( opt[l] > 0 )) && {
+        action="{print FILENAME; nextfile}"
+    }
+    (( opt[L] > 0 )) && {
+        prelude="BEGINFILE{flag=0};ENDFILE{if (flag==0)print FILENAME}; "
+        action="{flag=1; nextfile}"
+    }
+    prog="${prelude}${re} $action"
+    printf ${(qq)prog}
 }
 
-stuffs() {
-    local replacement_line REPLY REPLY2 flag
+main() {
+    # Needs to be in its own scope, to not have the variables leak to
+    # the main shell process. 
+    local replacement_line REPLY REPLY2 flag cursor
     local -a reply
+    typeset -A opt
 
-    # Store line in $reply[@], and some postitional info: 
+    # Store line in $reply[@]:
     split-shell-arguments
-    #current_word=$REPLY
-    #current_pos=$REPLY2
 
     flag=0
-    #echo ${(#)reply[@]}
-    for (( i=1; i<=$#reply; i++)); do 
-        #echo pre $i ${(qq)reply[$i]} >>log
-        if (( i%2==1 )); then
-            # This is spacing. 
-            continue
-        elif [[ $reply[$i] = "grep" || $reply[$i] = "egrep" ]]; then
-            # TODO: Generalize for some grep commands, aliases, etc.
-            flag=1
-            reply[$i]="awk"
+    cursor=0
+    for (( i=1; i<=$#reply; i++ )); do 
+        if (( i%2==1 && flag < 2 )); then
+            # Uneven "words" are whitespace. Only interested in changing the
+            # cursor position if exchanging the regex is not replaced by the awk
+            # program yet (flag < 2). 
+            len=$#reply[$i]
+            (( cursor += len ))
+        elif [[ $flag = 0 ]]; then
+            case $reply[$i] in
+                (grep)
+                    flag=1
+                    (( cursor += 3 ))
+                    reply[$i]="awk"
+                    ;;
+                (egrep)
+                    flag=1
+                    (( cursor += 3 ))
+                    reply[$i]="awk"
+                    opt[extended]++
+                    ;;
+                (pgrep)
+                    flag=1
+                    (( cursor += 3 ))
+                    reply[$i]="awk"
+                    opt[pcre]++
+                    ;;
+            esac
         elif [[ $flag = 1 && $reply[$i] = -* ]]; then
             # It an option to grep? 
             # If so, deal with the option. 
-            # for ((l=2; l<=$reply[$i]; $l++)); do
-            #     #check those options!
-            #     case $reply[$i][$l] in
-            #         (v)
-            #             opt["inverse"]
-            #             ;;
-            #         (w)
-            #             opt["wordmatch"]
-            #             ;;
-            #         (-)
-            #             continue
-            #             ;;
-            #     esac
-            # done
+            for ((l=1; l<$#reply[$i]; l++)); do
+                #check those options!
+                case ${reply[$i]:$l:1} in
+                    (v) typeset "opt[v]"=1
+                        ;;
+                    (w) typeset "opt[w]"=1
+                        ;;
+                    (l) typeset "opt[l]"=1
+                        ;;
+                    (L) typeset "opt[L]"=1
+                        ;;
+                    (x) typeset "opt[x]"=1
+                        ;;
+                    (H) typeset "opt[H]"=1
+                        ;;
+                    (*) continue
+                        ;;
+                esac
+            done
 
-            # For now: Delete the options:
+            # For now: Delete the options, and the now superfluous whitespace:
             reply[$i]=""
+            reply[$i+1]=""
+            # And leave the cursor pointer where it was. 
 
-            # Possibly something about removing spaces from the whitespace 
-            # around this thing...
         elif [[ $flag = 1 ]]; then
-            # This is the regex!
-            flag=0     # do not consider extra `-e`-s
-            # Now we know what options are there to modify the regex. 
-            # What options will be relevant? 
-            #  * -v
+            # This is the regex. Replace with the awk program. 
+            
             reply[$i]=$(change_regex $reply[$i])
+            (( cursor += $#reply[$i] - 2 ))
+            flag=2
         fi
-        #echo post $i ${(qq)reply[$i]} >>log
-    done
-
-    for (( i=1; i<=$#reply; i++ )); do
+        # Append the current version of $reply[$i] to replacement_line: 
         replacement_line+=$reply[$i]
     done
 
+    # Now we are done. Apply the changes to the BUFFER:
     BUFFER="$replacement_line"
+    CURSOR=cursor
 }
-stuffs
+main
